const DASHBOARD_HOME = '/dashboard';
const DASHBOARD_DETAIL = '/dashboard/detail';
const DASHBOARD_LOGIN = '/';
const DASHBOARD_FORGOT = '/forgot';

const PRIVATE_ROUTES = [DASHBOARD_HOME, DASHBOARD_DETAIL];
const AUTH_ROUTES = [DASHBOARD_LOGIN, DASHBOARD_FORGOT];

export {
	DASHBOARD_HOME,
	DASHBOARD_LOGIN,
	DASHBOARD_DETAIL,
	PRIVATE_ROUTES,
	AUTH_ROUTES,
};
